
package com.eccang.wsclient.rank;

import com.eccang.spider.base.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "KeywordRankWSService", targetNamespace = "http://cxf.eccang.com/", wsdlLocation = "http://192.168.100.109:8080/eccang/ws/keywordRank?wsdl")
public class KeywordRankWSService
        extends Service {

    private final static URL KEYWORDRANKWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException KEYWORDRANKWSSERVICE_EXCEPTION;
    private final static QName KEYWORDRANKWSSERVICE_QNAME = new QName("http://cxf.eccang.com/", "KeywordRankWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String value = PropertyUtil.getValue("ws.properties", "spiderWSIPPort");
            url = new URL(value + "/eccang/ws/keywordRank?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        KEYWORDRANKWSSERVICE_WSDL_LOCATION = url;
        KEYWORDRANKWSSERVICE_EXCEPTION = e;
    }

    public KeywordRankWSService() {
        super(__getWsdlLocation(), KEYWORDRANKWSSERVICE_QNAME);
    }

    public KeywordRankWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KEYWORDRANKWSSERVICE_QNAME, features);
    }

    public KeywordRankWSService(URL wsdlLocation) {
        super(wsdlLocation, KEYWORDRANKWSSERVICE_QNAME);
    }

    public KeywordRankWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KEYWORDRANKWSSERVICE_QNAME, features);
    }

    public KeywordRankWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeywordRankWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns KeywordRankWS
     */
    @WebEndpoint(name = "KeywordRankWSPort")
    public KeywordRankWS getKeywordRankWSPort() {
        return super.getPort(new QName("http://cxf.eccang.com/", "KeywordRankWSPort"), KeywordRankWS.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns KeywordRankWS
     */
    @WebEndpoint(name = "KeywordRankWSPort")
    public KeywordRankWS getKeywordRankWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.eccang.com/", "KeywordRankWSPort"), KeywordRankWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KEYWORDRANKWSSERVICE_EXCEPTION != null) {
            throw KEYWORDRANKWSSERVICE_EXCEPTION;
        }
        return KEYWORDRANKWSSERVICE_WSDL_LOCATION;
    }

}
