
package com.eccang.wsclient.validate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IImageOCRService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IImageOCRService {


    /**
     * 
     * @param type
     * @param url
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVerCodeFromUrl", action = "http://tempuri.org/IImageOCRService/GetVerCodeFromUrl")
    @WebResult(name = "GetVerCodeFromUrlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVerCodeFromUrl", targetNamespace = "http://tempuri.org/", className = "com.eccang.wsclient.validate.GetVerCodeFromUrl")
    @ResponseWrapper(localName = "GetVerCodeFromUrlResponse", targetNamespace = "http://tempuri.org/", className = "com.eccang.wsclient.validate.GetVerCodeFromUrlResponse")
    public String getVerCodeFromUrl(
        @WebParam(name = "Url", targetNamespace = "http://tempuri.org/")
        String url,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

    /**
     * 
     * @param imageString
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVerCodeFromImageString", action = "http://tempuri.org/IImageOCRService/GetVerCodeFromImageString")
    @WebResult(name = "GetVerCodeFromImageStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVerCodeFromImageString", targetNamespace = "http://tempuri.org/", className = "com.eccang.wsclient.validate.GetVerCodeFromImageString")
    @ResponseWrapper(localName = "GetVerCodeFromImageStringResponse", targetNamespace = "http://tempuri.org/", className = "com.eccang.wsclient.validate.GetVerCodeFromImageStringResponse")
    public String getVerCodeFromImageString(
        @WebParam(name = "ImageString", targetNamespace = "http://tempuri.org/")
        String imageString,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

}
