
package com.eccang.wsclient.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ec", targetNamespace = "http://www.example.org/Ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ec {


    /**
     * 
     * @param platformCode
     * @param token
     * @param customerCode
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.example.org/Ec/pushMessage")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "pushMessage", targetNamespace = "http://www.example.org/Ec/", className = "com.eccang.wsclient.api.PushMessage")
    @ResponseWrapper(localName = "pushMessageResponse", targetNamespace = "http://www.example.org/Ec/", className = "com.eccang.wsclient.api.PushMessageResponse")
    public String pushMessage(
        @WebParam(name = "customerCode", targetNamespace = "")
        String customerCode,
        @WebParam(name = "platformCode", targetNamespace = "")
        String platformCode,
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "data", targetNamespace = "")
        String data);

}
