
package com.eccang.wsclient.business;

import com.eccang.spider.base.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerBusinessWSService", targetNamespace = "http://relation.cxf.eccang.com/", wsdlLocation = "http://192.168.100.109:8080/eccang/ws/customerBusiness?wsdl")
public class CustomerBusinessWSService
    extends Service
{

    private final static URL CUSTOMERBUSINESSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERBUSINESSWSSERVICE_EXCEPTION;
    private final static QName CUSTOMERBUSINESSWSSERVICE_QNAME = new QName("http://relation.cxf.eccang.com/", "CustomerBusinessWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String value = PropertyUtil.getValue("ws.properties", "spiderWSIPPort");
            url = new URL(value + "/eccang/ws/customerBusiness?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERBUSINESSWSSERVICE_WSDL_LOCATION = url;
        CUSTOMERBUSINESSWSSERVICE_EXCEPTION = e;
    }

    public CustomerBusinessWSService() {
        super(__getWsdlLocation(), CUSTOMERBUSINESSWSSERVICE_QNAME);
    }

    public CustomerBusinessWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERBUSINESSWSSERVICE_QNAME, features);
    }

    public CustomerBusinessWSService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERBUSINESSWSSERVICE_QNAME);
    }

    public CustomerBusinessWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERBUSINESSWSSERVICE_QNAME, features);
    }

    public CustomerBusinessWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerBusinessWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerBusinessWS
     */
    @WebEndpoint(name = "CustomerBusinessWSPort")
    public CustomerBusinessWS getCustomerBusinessWSPort() {
        return super.getPort(new QName("http://relation.cxf.eccang.com/", "CustomerBusinessWSPort"), CustomerBusinessWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerBusinessWS
     */
    @WebEndpoint(name = "CustomerBusinessWSPort")
    public CustomerBusinessWS getCustomerBusinessWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://relation.cxf.eccang.com/", "CustomerBusinessWSPort"), CustomerBusinessWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERBUSINESSWSSERVICE_EXCEPTION!= null) {
            throw CUSTOMERBUSINESSWSSERVICE_EXCEPTION;
        }
        return CUSTOMERBUSINESSWSSERVICE_WSDL_LOCATION;
    }

}
