
package com.eccang.wsclient.followsell;

import com.eccang.spider.base.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FollowSellWSService", targetNamespace = "http://followsell.cxf.eccang.com/", wsdlLocation = "http://localhost:8080/eccang/ws/followSell?wsdl")
public class FollowSellWSService
    extends Service
{

    private final static URL FOLLOWSELLWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FOLLOWSELLWSSERVICE_EXCEPTION;
    private final static QName FOLLOWSELLWSSERVICE_QNAME = new QName("http://followsell.cxf.eccang.com/", "FollowSellWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String value = PropertyUtil.getValue("ws.properties", "spiderWSIPPort");
            String productName = PropertyUtil.getValue("ws.properties", "productName");
            url = new URL(value + "/" + productName + "/ws/followSell?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        FOLLOWSELLWSSERVICE_WSDL_LOCATION = url;
        FOLLOWSELLWSSERVICE_EXCEPTION = e;
    }

    public FollowSellWSService() {
        super(__getWsdlLocation(), FOLLOWSELLWSSERVICE_QNAME);
    }

    public FollowSellWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FOLLOWSELLWSSERVICE_QNAME, features);
    }

    public FollowSellWSService(URL wsdlLocation) {
        super(wsdlLocation, FOLLOWSELLWSSERVICE_QNAME);
    }

    public FollowSellWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FOLLOWSELLWSSERVICE_QNAME, features);
    }

    public FollowSellWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FollowSellWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FollowSellWS
     */
    @WebEndpoint(name = "FollowSellWSPort")
    public FollowSellWS getFollowSellWSPort() {
        return super.getPort(new QName("http://followsell.cxf.eccang.com/", "FollowSellWSPort"), FollowSellWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FollowSellWS
     */
    @WebEndpoint(name = "FollowSellWSPort")
    public FollowSellWS getFollowSellWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://followsell.cxf.eccang.com/", "FollowSellWSPort"), FollowSellWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FOLLOWSELLWSSERVICE_EXCEPTION!= null) {
            throw FOLLOWSELLWSSERVICE_EXCEPTION;
        }
        return FOLLOWSELLWSSERVICE_WSDL_LOCATION;
    }

}
