
package com.eccang.wsclient.asin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AsinWS", targetNamespace = "http://cxf.eccang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AsinWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addToCrawl", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.AddToCrawl")
    @ResponseWrapper(localName = "addToCrawlResponse", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.AddToCrawlResponse")
    public String addToCrawl(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsins", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.GetAsins")
    @ResponseWrapper(localName = "getAsinsResponse", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.GetAsinsResponse")
    public String getAsins(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.eccang.wsclient.asin.BaseRspParam
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.AuthResponse")
    public BaseRspParam auth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPriority", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.SetPriority")
    @ResponseWrapper(localName = "setPriorityResponse", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.asin.SetPriorityResponse")
    public String setPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
