
package com.eccang.wsclient.customer;

import us.codecraft.webmagic.samples.base.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CustomerAsinWSService", targetNamespace = "http://cxf.eccang.com/", wsdlLocation = "http://localhost:8080/eccang/ws/customerAsin?wsdl")
public class CustomerAsinWSService
    extends Service
{

    private final static URL CUSTOMERASINWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERASINWSSERVICE_EXCEPTION;
    private final static QName CUSTOMERASINWSSERVICE_QNAME = new QName("http://cxf.eccang.com/", "CustomerAsinWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String value = PropertyUtil.getValue("ws.properties", "spiderWSIPPort");
            url = new URL(value + "/eccang/ws/customerAsin?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERASINWSSERVICE_WSDL_LOCATION = url;
        CUSTOMERASINWSSERVICE_EXCEPTION = e;
    }

    public CustomerAsinWSService() {
        super(__getWsdlLocation(), CUSTOMERASINWSSERVICE_QNAME);
    }

    public CustomerAsinWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERASINWSSERVICE_QNAME, features);
    }

    public CustomerAsinWSService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERASINWSSERVICE_QNAME);
    }

    public CustomerAsinWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERASINWSSERVICE_QNAME, features);
    }

    public CustomerAsinWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerAsinWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CustomerAsinWS
     */
    @WebEndpoint(name = "CustomerAsinWSPort")
    public CustomerAsinWS getCustomerAsinWSPort() {
        return super.getPort(new QName("http://cxf.eccang.com/", "CustomerAsinWSPort"), CustomerAsinWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerAsinWS
     */
    @WebEndpoint(name = "CustomerAsinWSPort")
    public CustomerAsinWS getCustomerAsinWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.eccang.com/", "CustomerAsinWSPort"), CustomerAsinWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERASINWSSERVICE_EXCEPTION!= null) {
            throw CUSTOMERASINWSSERVICE_EXCEPTION;
        }
        return CUSTOMERASINWSSERVICE_WSDL_LOCATION;
    }

}
