
package com.eccang.wsclient.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerAsinWS", targetNamespace = "http://cxf.eccang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerAsinWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setCrawl", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.customer.SetCrawl")
    @ResponseWrapper(localName = "setCrawlResponse", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.customer.SetCrawlResponse")
    public String setCrawl(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.eccang.wsclient.customer.BaseRspParam
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.customer.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://cxf.eccang.com/", className = "com.eccang.wsclient.customer.AuthResponse")
    public BaseRspParam auth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
