
package com.eccang.wsclient.pay;

import com.eccang.spider.base.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PayPackageWSService", targetNamespace = "http://pay.cxf.eccang.com/", wsdlLocation = "http://localhost:8080/eccang/ws/payPackage?wsdl")
public class PayPackageWSService
    extends Service
{

    private final static URL PAYPACKAGEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYPACKAGEWSSERVICE_EXCEPTION;
    private final static QName PAYPACKAGEWSSERVICE_QNAME = new QName("http://pay.cxf.eccang.com/", "PayPackageWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String value = PropertyUtil.getValue("ws.properties", "spiderWSIPPort");
            url = new URL(value + "/eccang/ws/payPackage?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        PAYPACKAGEWSSERVICE_WSDL_LOCATION = url;
        PAYPACKAGEWSSERVICE_EXCEPTION = e;
    }

    public PayPackageWSService() {
        super(__getWsdlLocation(), PAYPACKAGEWSSERVICE_QNAME);
    }

    public PayPackageWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYPACKAGEWSSERVICE_QNAME, features);
    }

    public PayPackageWSService(URL wsdlLocation) {
        super(wsdlLocation, PAYPACKAGEWSSERVICE_QNAME);
    }

    public PayPackageWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYPACKAGEWSSERVICE_QNAME, features);
    }

    public PayPackageWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayPackageWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PayPackageWS
     */
    @WebEndpoint(name = "PayPackageWSPort")
    public PayPackageWS getPayPackageWSPort() {
        return super.getPort(new QName("http://pay.cxf.eccang.com/", "PayPackageWSPort"), PayPackageWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayPackageWS
     */
    @WebEndpoint(name = "PayPackageWSPort")
    public PayPackageWS getPayPackageWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pay.cxf.eccang.com/", "PayPackageWSPort"), PayPackageWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYPACKAGEWSSERVICE_EXCEPTION!= null) {
            throw PAYPACKAGEWSSERVICE_EXCEPTION;
        }
        return PAYPACKAGEWSSERVICE_WSDL_LOCATION;
    }

}
