
package com.eccang.wsclient.review;

import com.eccang.spider.base.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReviewWSService", targetNamespace = "http://review.cxf.eccang.com/", wsdlLocation = "http://192.168.100.109:8080/eccang/ws/review?wsdl")
public class ReviewWSService
    extends Service
{

    private final static URL REVIEWWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException REVIEWWSSERVICE_EXCEPTION;
    private final static QName REVIEWWSSERVICE_QNAME = new QName("http://review.cxf.eccang.com/", "ReviewWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String value = PropertyUtil.getValue("ws.properties", "wsdlLocation");
            url = new URL(value + "/eccang/ws/review?wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        REVIEWWSSERVICE_WSDL_LOCATION = url;
        REVIEWWSSERVICE_EXCEPTION = e;
    }

    public ReviewWSService() {
        super(__getWsdlLocation(), REVIEWWSSERVICE_QNAME);
    }

    public ReviewWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVIEWWSSERVICE_QNAME, features);
    }

    public ReviewWSService(URL wsdlLocation) {
        super(wsdlLocation, REVIEWWSSERVICE_QNAME);
    }

    public ReviewWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVIEWWSSERVICE_QNAME, features);
    }

    public ReviewWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReviewWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReviewWS
     */
    @WebEndpoint(name = "ReviewWSPort")
    public ReviewWS getReviewWSPort() {
        return super.getPort(new QName("http://review.cxf.eccang.com/", "ReviewWSPort"), ReviewWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReviewWS
     */
    @WebEndpoint(name = "ReviewWSPort")
    public ReviewWS getReviewWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://review.cxf.eccang.com/", "ReviewWSPort"), ReviewWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REVIEWWSSERVICE_EXCEPTION!= null) {
            throw REVIEWWSSERVICE_EXCEPTION;
        }
        return REVIEWWSSERVICE_WSDL_LOCATION;
    }

}
